apiVersion: apps/v1
kind: Deployment
metadata:
  name: sbillt-deployment
  labels:
    app: sbillt
spec:
  replicas: 5
  selector:
    matchLabels:
      app: sbillt
  template:
    metadata:
      labels:
        app: sbillt
    spec:
      containers:
        - name: sbillt
          image: byuan333/sbillt
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: sbillt-service
spec:
  selector:
    app: sbillt
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30000
