apiVersion: apps/v1
kind: Deployment
metadata:
  name: sbillt-deployment-5
  labels:
    app: sbillt-5
spec:
  replicas: 5
  selector:
    matchLabels:
      app: sbillt-5
  template:
    metadata:
      labels:
        app: sbillt-5
    spec:
      containers:
        - name: sbillt-5
          image: byuan333/sbillt
          ports:
            - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: sbillt-test-service-5
spec:
  selector:
    app: sbillt-5
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
      nodePort: 30001
