apiVersion: apps/v1
kind: Deployment
metadata:
  name: sbillt-deployment-1
  labels:
    app: sbillt-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sbillt-1
  template:
    metadata:
      labels:
        app: sbillt-1
    spec:
      containers:
        - name: sbillt-1
          image: byuan333/sbillt
          ports:
            - containerPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: sbillt-test-service-1
spec:
  selector:
    app: sbillt-1
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
      nodePort: 30002
